metrics_dict:
  accuracy: Accuracy
  balanced_accuracy: Balanced Accuracy
  roc_auc: ROC AUC
  f1: F1 Score
  precision: Precision
  recall: Recall
  log_loss: Log Loss
  average_precision: Average Precision
  root_mean_squared_error: Root Mean Squared Error
  mean_squared_error: Mean Squared Error
  mean_absolute_error: Mean Absolute Error
  r2: R^2
  pearsonr: Pearson R
  spearmanr: Spearman R

ag_models:
  CAT: CatBoost        # CAT -> CatBoost
  GBM: LightGBM        # GBM -> LightGBM
  RF: RandomForestGini # RF -> RandomForestGini
  XT: ExtraTreesGini   # XT -> ExtraTreesGini
  XGB: XGBoost         # XGB -> XGBoost
  FASTAI: NeuralNetFastAI    # FASTAI -> fastai NN
  NN_TORCH: PyTorchNN        # (например, если хотите Torch)
  LR: "Linear scikit"        # линейная модель
  KNN: "KNearestNeighbors"    # ...

  # Add more models if needed    # ...

presets_list:
  - fast_training
  - medium_quality
  - high_quality
  - best_quality
  - good_quality
  - optimize_for_deployment
  - experimental